{% set version = "1.11.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bayesplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bayesplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bayesplot/bayesplot_{{ version }}.tar.gz
  sha256: 4f71e67391e0135acd3e890989b87025f3f8160242f532a8e1a0ed74ed0f3830

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=0.8.0
    - r-ggplot2 >=3.0.0
    - r-ggridges
    - r-glue
    - r-posterior
    - r-reshape2
    - r-rlang >=0.3.0
    - r-tibble >=2.0.0
    - r-tidyselect
  run:
    - r-base
    - r-dplyr >=0.8.0
    - r-ggplot2 >=3.0.0
    - r-ggridges
    - r-glue
    - r-posterior
    - r-reshape2
    - r-rlang >=0.3.0
    - r-tibble >=2.0.0
    - r-tidyselect

test:
  commands:
    - $R -e "library('bayesplot')"           # [not win]
    - "\"%R%\" -e \"library('bayesplot')\""  # [win]

about:
  home: https://mc-stan.org/bayesplot
  license: GPL-3.0-or-later
  summary: Plotting functions for posterior analysis,  prior and posterior predictive checks, and MCMC diagnostics.  The package is designed not only to provide convenient functionality  for users, but also a common set of functions that can be easily used by  developers working on a variety of R packages for Bayesian modeling,  particularly
    (but not exclusively) packages interfacing with 'Stan'.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bayesplot
# Type: Package
# Title: Plotting for Bayesian Models
# Version: 1.7.0
# Date: 2019-05-22
# Authors@R: c(person("Jonah", "Gabry", role = c("aut", "cre"), email = "jsg2201@columbia.edu"), person("Tristan", "Mahr", role = "aut"), person("Paul-Christian", "Burkner", role = "ctb"), person("Martin", "Modrak", role = "ctb"), person("Malcolm", "Barrett", role = "ctb"))
# Maintainer: Jonah Gabry <jsg2201@columbia.edu>
# Description: Plotting functions for posterior analysis,  prior and posterior predictive checks, and MCMC diagnostics.  The package is designed not only to provide convenient functionality  for users, but also a common set of functions that can be easily used by  developers working on a variety of R packages for Bayesian modeling,  particularly (but not exclusively) packages interfacing with 'Stan'.
# License: GPL (>= 3)
# LazyData: TRUE
# URL: https://mc-stan.org/bayesplot
# BugReports: https://github.com/stan-dev/bayesplot/issues/
# SystemRequirements: pandoc (>= 1.12.3), pandoc-citeproc
# Depends: R (>= 3.1.0)
# Imports: dplyr (>= 0.8.0), ggplot2 (>= 2.2.1), ggridges, glue, reshape2, rlang (>= 0.3.0), stats, tibble, tidyselect, utils
# Suggests: gridExtra (>= 2.2.1), hexbin, knitr (>= 1.16), loo (>= 2.0.0), RColorBrewer, rmarkdown (>= 1.0.0), rstan (>= 2.17.1), rstanarm (>= 2.17.4), rstantools (>= 1.5.0), scales, shinystan (>= 2.3.0), testthat (>= 2.0.0), vdiffr
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-05-22 18:59:18 UTC; jgabry
# Author: Jonah Gabry [aut, cre], Tristan Mahr [aut], Paul-Christian Burkner [ctb], Martin Modrak [ctb], Malcolm Barrett [ctb]
# Repository: CRAN
# Date/Publication: 2019-05-23 04:50:03 UTC
