appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: G9vkSfnK6Mx9eRi0LBrcQzSMWbVSZeCYNlspdV3VaM+bVVupDPnIbNdpBJYUVtDrAG9fsdzwn8OI8vpIHoNOj7Q/0Rba5FzDlERQ2DF4I6CSaC/tz5ecM1eLHgXBTCvJofn6+nIPDsUlTMionxSOm46wqo53EJvbND4/dqDDcqEpFoDMz5UJmrtFKh+VlW9BufZ+2WzEAL0I0N4qAfHbxba+rzHT0y1C7qkMJsyVB40REdQhDVbnKb4qOU1FSXaPZhHq4VLiqg5qyg544KBLtlXpzVtVqdBC1F/GOlbt77+0Q4bfs0s6wmVV4YlrGrF17sqUCkADj+b0zS7wfJWBsz+xFmZtUAZupju3TvI4z2a2z7ZZaLwqIqrM6M6PwMgHGpYAcA1Mc8ZlUalvI1JgCtzCkCdraVF8Gc/HcqG89ZyGyP2D7d4ktTWtaUZAQslD4R/1xWVtnlGdP6oSvGlPSIi+vEFW9yKSE+xpdomS5GQQmvnncGV4/noU3VHB5yUipV85O0it2QJCRHxuAKpEB+nO9x+V8TmTPwyV/cJ5aG5LO+Durbu2cGsvda7FZitvUWwYUdPrL7zFAzIrtnNLSdIK4x+xHHeZjUWxIXw77mbk2i4vMqhUXgntyMrgXgME+YGKz8CEt14vTpR7I5BsSUjcjqacBpoRWwrh8dQMzmI=}
bot:
  automerge: true
