travis:
  secure:
    BINSTAR_TOKEN: Do/0KinrL7n7mSVU7Xi11v3/MzA9IpZajL43n9hOxIxKRj36DrS8kDn8wfd9eqGfIAAuTFpAymeo5Dj4UtBD6w14aeJyfI76iE/hXdnESoZosE7UcZcItCKcW4OwDu9alhmDm9zPh/mgquUW+/DvFQmH4bN7KxNaks4h7Kfw2PnqU5JWJoNos7Cg1uAmj/zDEjTKoDGunKzECWlCZ9NCBe/MSyXzFo5BtH69LRNH8cf8CdN8IZbLMnllxEcDOi8O6MQ7xF4lUZDXL7LTnWNcDgzungFPjv5JHefjrQlCV1ERS+tJRSUScww58PY2gvJH4WSAkD8NhiYYzWHBdaLpge++tZFwddmBkW8jMRsCohdmimHs1yLJLeR9+wCE59jKw8M498f6mz31Hy5tevygT9PvO2YROWKp8F/iIsvppARcMH5Uj4qkYZd5fn97//2exk7m+rtELfqSFoZovydUUkbjfBKFHJQYuKweGuAq/AOQfYLsPN7Lhq5RxAtET+yW2H7PHH9viqThGjRiyhJBAbNmtXwWDYxTMyjpZ6p8UU8RgT5HlPtP7kNJBzqv+lWfmo1IE0oLC8DjfDdcp3/SG2Xd8iIHXj2smEsv2bMBKCPhvQAyXwWK5Pplv1otTmqlYmENKSeyWjbNlzUnQiLsaeUafw2jt0vi2ejWFdpv8rQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
